### ISSUE TITLE
Invalid ELF Header

### ISSUE THREAD

**Issue by filipetrocadoferreira** [cvlab-epfl/pyKSP#1]
Hi, I'm having this error when trying to run the example:

ImportError: pyKSP/ksp.so: invalid ELF header

I run the .cpp example fine

**Comment by pierrebaque** [comment]
Hello,

Did you try recompiling everything?

Cheers,
Pierre

**Comment by filipetrocadoferreira** [comment]
Hi Pierre, thanks for answering. Yes, I recompiled and tested the c++ module  and it runs ok

**Comment by filipetrocadoferreira** [comment]
The c++ module runs, but not the Python import...

**Comment by filipetrocadoferreira** [comment]
ok , this works, just make sure you delete all .so files bfr make

**Comment by pierrebaque** [comment]
Hello @filipetrocadoferreira ,

Thanks for your contribution!

Cheers,
Pierre
